# Generated by Django 5.1.7 on 2025-03-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteka", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fiction", "Fiction"),
                    ("action", "Action"),
                    ("adventure", "Adventure"),
                    ("animation", "Animation"),
                    ("comedy", "Comedy"),
                    ("drama", "Drama"),
                    ("fantasy", "Fantasy"),
                    ("horror", "Horror"),
                    ("music", "Music"),
                ],
                max_length=255,
            ),
        ),
    ]
