# Generated by Django 5.1.7 on 2025-03-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                blank=True,
                help_text="13 Character ISBN number",
                max_length=13,
                null=True,
            ),
        ),
    ]
