# Generated by Django 5.1.7 on 2025-03-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_review_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
