# Generated by Django 5.1.7 on 2025-03-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_alter_genre_slug"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tags.tag"),
        ),
    ]
