# Generated by Django 5.1.7 on 2025-03-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_book_tags"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="tags.tag"
            ),
        ),
    ]
